# Generated by Django 6.0.1 on 2026-01-21 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("data_nascimento", models.DateField()),
                ("observacao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="cargo",
            field=models.CharField(
                choices=[("D", "Dentista"), ("S", "Secretária"), ("A", "Admin")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("procedimento", models.CharField(max_length=100)),
                (
                    "dentista",
                    models.ForeignKey(
                        limit_choices_to={"cargo": "D"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.paciente",
                    ),
                ),
            ],
        ),
    ]
